dist: trusty
sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.23.0
script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "1.23.0" ]; then
        cargo test --verbose;
        cargo doc --verbose --no-deps;
      else
        cargo test --verbose;
        cargo test --verbose --no-default-features;
        cargo doc --verbose;
      fi
