dist: trusty
sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.23.0
script:
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" != "1.23.0" ]; then cargo test --verbose --no-default-features; fi
  - cargo doc --verbose
