[package]
name = "osmpbf"
version = "0.1.3"
authors = ["Johannes Hofmann <mail@b-r-u.org>"]
readme = "README.md"
repository = "https://github.com/b-r-u/osmpbf"
homepage = "https://github.com/b-r-u/osmpbf"
description = """
A reader for the OpenStreetMap PBF file format (*.osm.pbf).
"""
categories = ["parser-implementations", "encoding", "science"]
keywords = ["openstreetmap", "osm", "pbf", "protocolbuffer", "protobuf"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "b-r-u/osmpbf" }
appveyor = { repository = "b-r-u/osmpbf" }

[features]
default = ["system-libz"]
system-libz = ["flate2"]

[dependencies]
protobuf = "1.4"
byteorder = "1.1"
flate2 = { version = "0.2", optional = true }
inflate = "0.3"
error-chain = "0.11"
memmap = "0.6"
rayon = "0.9"
